name: deploy-front
on:
  workflow_dispatch:

jobs:
  build-job:
    name: Deploy Front
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Wait for SSH'
        run: |
          while ! nc -w5 -z ${{ secrets.INSTANCE_IP }} 22; do
                  sleep 5
                  echo "SSH not available..."
          done; echo "SSH ready!"

      - name: 'Creating Env File'
        run: 'echo "$ENV_FILE" > .env'
        shell: bash
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: 'Push Repo'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.VM_SSH_PRIVATE_KEY_PASSPHRASE }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          source: "./"
          target: /home/${{ secrets.SSH_USERNAME }}/deploys/${{ github.event.repository.name }}

      - name: 'Start Front'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.VM_SSH_PRIVATE_KEY_PASSPHRASE }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
            cd /home/${{ secrets.SSH_USERNAME }}/deploys/${{ github.event.repository.name }}
            rm -rf ./node_modules ./dist .env
            npm install
            npm run build
            sudo rm -rf ${{ secrets.DEPLOY_FOLDER }}/*
            sudo rsync --ignore-times -a dist/ ${{ secrets.DEPLOY_FOLDER }}/
